#' Plot values for a protein of interest
#'
#' \code{plot_single} generates a barplot of a protein of interest.
#'
#' @param data SummerizedExperiment, Data object which has been generated by \code{\link{linear_model}} and \code{\link{cutoffs}}.
#' @param protein Character, Protein name.
#' @param type "centered" or "contrast", The type of data scaling used for plotting.
#' @return A barplot (generated by \code{\link{ggplot}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' example_vsn <- norm_vsn(example_filter)
#' example_impute <- imputation(example_filter, fun = "MinProb", q = 0.01)
#'
#' example_lm <- linear_model(example_impute, "Ctrl", "control")
#' example_sign <- cutoffs(example_lm, alpha = 0.05, lfc = 1)
#'
#' plot_single(example_sign, "USP15", "centered")
#' plot_single(example_sign, "USP15", "contrast")
#' @export
plot_single <- function(data, protein, type) {

  # Show error if an unvalid protein name is given
  if(length(which(rowData(data)$name == protein)) == 0) {
    possibilities <- rowData(data)$name[grep(substr(protein, 1, nchar(protein)-1), rowData(data)$name)]
    if (length(possibilities) > 0){
      possibilities_msg <- paste0("Do you mean: '", paste0(possibilities, collapse = "', '"), "'")
    } else { possibilities_msg <- NULL}
    stop(
      "Not a valid protein, please run `plot_single()` with a valid protein name as argument\n",
      possibilities_msg,
      call. = FALSE)
  }

  # Plot either the average protein-centered enrichment values per condition ("centered") or
  # the average enrichments of conditions versus the control condition ("contrast") for a single protein
  if(type == "centered") {
    # Obtain protein-centered enrichment values
    df <- assay(data) - rowData(data)$mean
    df %<>% data.frame(.) %>% rownames_to_column(.)
    # Select values for a single protein in long format and add sample annotation
    df %<>% filter(rowname == protein) %>% gather(ID, val, 2:ncol(.)) %>% left_join(., data.frame(colData(data)), by = "ID")
    df$replicate <- as.factor(df$replicate)
    # Plot the centered enrichment values for the replicates as well as the mean
    p1 <- ggplot(df, aes(condition, val, col = replicate)) + geom_hline(yintercept = 0) + theme_bw() +
      stat_summary(fun.y = "mean", colour = "black", size = 0, geom = "bar", fill = "black") +
      geom_point(shape = 17, size = 4) + labs(title = unique(df$rowname), x = "Baits", y = "Enrichment (log2)") +
      theme(axis.text=element_text(size=12), axis.text.x = element_text(angle = 90, hjust = 1), axis.title=element_text(size=14,face="bold"), legend.text=element_text(size=12), legend.title = element_text(size=14,face="bold"), legend.position="top")
  }
  if(type == "contrast") {
    # Obtain average enrichments of conditions versus the control condition
    df <- rowData(data) %>% data.frame() %>% column_to_rownames(var = "name") %>% select(ends_with("_diff")) %>% rownames_to_column(.)
    colnames(df)[2:ncol(df)] %<>%  gsub("_diff", "", .) %>% gsub("_vs_", " - ", .)
    # Select values for a single protein in long format
    df %<>% filter(rowname == protein) %>% gather(condition, LFC, 2:ncol(.))
    # Plot the average enrichments of conditions versus the control condition
    p1 <- ggplot(df, aes(condition, LFC)) + geom_hline(yintercept = 0) + theme_bw() +
      geom_bar(stat = "unique", size = 0, col = "black", fill = "black") + labs(title = unique(df$rowname), x = "", y = "Enrichment (log2)") +
      theme(axis.text=element_text(size=12), axis.text.x = element_text(angle = 90, hjust = 1), axis.title=element_text(size=14,face="bold"), legend.text=element_text(size=12), legend.title = element_text(size=14,face="bold"), legend.position="top")
  }
  p1
}

#' Plot a heatmap
#'
#' \code{plot_heatmap} generates a heatmap of all significant proteins.
#'
#' @param data SummerizedExperiment, Data object which has been generated by \code{\link{linear_model}} and \code{\link{cutoffs}}.
#' @param type "centered" or "contrast", The type of data scaling used for plotting.
#' @param k Integer, sets the number of k-means clusters.
#' @param col_limit Integer, sets the outer limits of the color scale.
#' @param labelsize Integer, sets the size of name labels.
#' @return A heatmap (generated by \code{\link{Heatmap}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' example_vsn <- norm_vsn(example_filter)
#' example_impute <- imputation(example_filter, fun = "MinProb", q = 0.01)
#'
#' example_lm <- linear_model(example_impute, "Ctrl", "control")
#' example_sign <- cutoffs(example_lm, alpha = 0.05, lfc = 1)
#'
#' plot_heatmap(example_sign, "centered", k = 6, col_limit = 4, labelsize = 3)
#' plot_heatmap(example_sign, "contrast", k = 6, col_limit = 10, labelsize = 3)
#' @export
plot_heatmap <- function(data, type, k = 6, col_limit = 6, labelsize = 10) {
  # Filter for significant proteins only
  data <- data[rowData(data)$sign == "+", ]

  # Plot a heatmap of the average protein-centered enrichment values per condition ("centered") or
  # the average enrichments of conditions versus the control condition ("contrast")
  if(type == "centered") {
    # Obtain protein-centered enrichment values
    df <- assay(data) - rowData(data)$mean

    # Perform k-means clustering
    set.seed(1)
    kmeans <- kmeans(df,k)
    # Order the k-means clusters according to the maximum enrichment in all samples averaged over the proteins in the cluster
    order <- df %>% data.frame() %>% cbind(., cluster = kmeans$cluster) %>% mutate(row = apply(.[,1:(ncol(.)-1)], 1, function(x) max(x))) %>% group_by(cluster) %>% summarize(index=sum(row)/n()) %>% arrange(desc(index)) %>% collect %>% .[[1]] %>% match(seq(1:k),.)
    kmeans$cluster <- order[kmeans$cluster]
  }
  if(type == "contrast") {
    # Obtain average enrichments of conditions versus the control condition
    df <- rowData(data) %>% data.frame() %>% column_to_rownames(var = "name") %>% select(ends_with("_diff"))
    colnames(df) %<>% gsub("_diff","" , .) %>% gsub("_vs_", " - ", .)

    # Perform k-means clustering
    set.seed(1)
    kmeans <- kmeans(df,k)
    # Order the k-means clusters according to their average enrichment
    order <- cbind(df, cluster = kmeans$cluster) %>% gather(condition, diff, 1:(ncol(.)-1)) %>% group_by(cluster) %>% summarize(row = mean(diff)) %>% arrange(desc(row)) %>% collect %>% .[[1]] %>% match(seq(1:k),.)
    kmeans$cluster <- order[kmeans$cluster]
  }

  # Plot the heatmap
  ht1 = Heatmap(df, col = circlize::colorRamp2(seq(-col_limit, col_limit, (col_limit/5)), rev(RColorBrewer::brewer.pal(11, "RdBu"))), split = kmeans$cluster,
                cluster_columns = T, cluster_rows = T, na_col = "grey", clustering_distance_rows = "pearson",clustering_distance_columns = "pearson",
                row_names_side = "left", column_names_side = "top", show_row_names = T, show_column_names = T,
                heatmap_legend_param = list(color_bar = "continuous", legend_direction = "horizontal", legend_width = unit(5, "cm"), title_position = "lefttop"),
                name = "Enrichment (Log2)", row_names_gp = gpar(fontsize = labelsize), column_names_gp = gpar(fontsize = 16))
  draw(ht1, heatmap_legend_side = "top")
}

#' Volcano plot
#'
#' \code{plot_volcano} generates a volcano plot for a specified contrast.
#'
#' @param data SummerizedExperiment, Data object which has been generated by \code{\link{linear_model}} and \code{\link{cutoffs}}.
#' @param contrast Character, The specific contrast to plot.
#' @param labelsize Integer, sets the size of name labels.
#' @param add_names Boolean, whether or not to plot names.
#' @return A volcano plot (generated by \code{\link{ggplot}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' example_vsn <- norm_vsn(example_filter)
#' example_impute <- imputation(example_filter, fun = "MinProb", q = 0.01)
#'
#' example_lm <- linear_model(example_impute, "Ctrl", "control")
#' example_sign <- cutoffs(example_lm, alpha = 0.05, lfc = 1)
#'
#' plot_volcano(example_sign, "Ubi6_vs_Ctrl", labelsize = 5, add_names = T)
#' plot_volcano(example_sign, "Ubi6_vs_Ctrl", add_names = F)
#' plot_volcano(example_sign, "Ubi4_vs_Ctrl", labelsize = 5, add_names = T)
#' plot_volcano(example_sign, "Ubi4_vs_Ctrl", add_names = F)
#' @export
plot_volcano <- function(data, contrast, labelsize = 3, add_names = TRUE) {
  row_data <- rowData(data)

  # Show error if an unvalid contrast is given
  if(length(grep(paste(contrast, "_diff", sep = ""), colnames(row_data))) == 0) {
    valid_cntrsts <- row_data %>% data.frame() %>% select(ends_with("_diff")) %>% colnames(.) %>% gsub("_diff", "", .)
    valid_cntrsts_msg <- paste0("Valid contrasts are: '", paste0(valid_cntrsts, collapse = "', '"), "'")
    stop(
      "Not a valid contrast, please run `plot_volcano()` with a valid contrast as argument\n",
      valid_cntrsts_msg,
      call. = FALSE)
    }

  # Generate a data.frame containing all info for the volcano plot
  diff <- grep(paste(contrast, "_diff", sep = ""), colnames(row_data)) # All log2 fold change columns
  padj <- grep(paste(contrast, "_p.adj", sep = ""), colnames(row_data)) # All adjusted p-value columns
  sign <- grep(paste(contrast, "_sign", sep = ""), colnames(row_data)) # All significance columns
  df <- data.frame(x = row_data[,diff], y = -log10(row_data[,padj]) , z = row_data[,sign], name = row_data$name)
  sign <- df %>% filter(z == "+")
  name1 <- gsub("_vs_.*", "", contrast)
  name2 <- gsub(".*_vs_", "", contrast)

  # Plot volcano with or without labels
  if(add_names) {
    p1 <- ggplot(df, aes(x, y)) + geom_vline(xintercept = 0) + geom_point(col = "grey") + geom_point(data = sign, col = "black") + ggrepel::geom_text_repel(data = sign, aes(label = name), size = labelsize, point.padding = unit(0.3, "lines")) + theme_bw() +
      theme(legend.position="none", axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold")) + labs(x = "Log2 Fold Change", y = "-log10 adjusted P value") +
      geom_text(data = data.frame(), aes(x = c(Inf, -Inf), y = c(-Inf, -Inf), hjust = c(1, 0), vjust = c(-1, -1), label = c(name1, name2), size = 5, fontface = "bold"))
  } else {
    p1 <- ggplot(df, aes(x, y)) + geom_vline(xintercept = 0) + geom_point(col = "grey") + geom_point(data = sign, col = "black") + theme_bw() +
      theme(legend.position="none", axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold")) + labs(x = "Log2 Fold Change", y = "-log10 adjusted P value") +
      geom_text(data = data.frame(), aes(x = c(Inf, -Inf), y = c(-Inf, -Inf), hjust = c(1, 0), vjust = c(-1, -1), label = c(name1, name2), size = 5, fontface = "bold"))
  }
  p1
}

#' Visualize normalization
#'
#' \code{plot_norm} generates boxplots for all conditions before and after normalization.
#'
#' @param raw SummerizedExperiment, Data object before normalization.
#' @param norm SummerizedExperiment, Data object after normalization by \code{\link{norm_vsn}}.
#' @return Boxplots for all conditions before and after normalization (generated by \code{\link{ggplot}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' example_vsn <- norm_vsn(example_filter)
#'
#' plot_norm(example_filter, example_vsn)
#' @export
plot_norm <- function(raw, norm) {
  # Get a long data.frame of the assay data (original and normalized) annotated with sample info
  df1 <- assay(raw) %>% data.frame() %>% rownames_to_column(.) %>% gather(ID, val, 2:ncol(.)) %>% left_join(., data.frame(colData(raw)), by = "ID") %>% mutate(var = "original")
  df2 <- assay(norm) %>% data.frame() %>% rownames_to_column(.) %>% gather(ID, val, 2:ncol(.)) %>% left_join(., data.frame(colData(norm)), by = "ID") %>% mutate(var = "normalized")
  df <- rbind(df1, df2)
  # Boxplots for conditions with facet_wrap for the original and normalized values
  ggplot(df, aes(x = ID, y = val, fill = condition)) + geom_boxplot(notch = T, na.rm=TRUE) + coord_flip() + facet_wrap(~var, ncol = 1) + theme_bw() + labs(x = "", y = "Log2 Intensity") +
    theme(axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold"), legend.text=element_text(size=12), legend.title = element_text(size=14,face="bold"), legend.position="right")
}

#' Plot a heatmap of proteins with missing values
#'
#' \code{plot_missval} generates a heatmap of proteins with missing values to discover whether values are missing by random or not.
#'
#' @param data SummerizedExperiment, Data object which has been generated by \code{\link{linear_model}} and \code{\link{cutoffs}}.
#' @return A heatmap indicating whether values are missing (0) or not (1) (generated by \code{\link{Heatmap}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' plot_missval(example_filter)
#' @export
plot_missval <- function(data) {
  # Make assay data binary (1 = valid value, 0 = missing value)
  df <- assay(data) %>% data.frame(.)
  missval <- df[apply(df, 1, function(x) any(is.na(x))),]
  missval <- ifelse(is.na(missval), 0, 1)
  # Plot binary heatmap
  ht2 = Heatmap(missval, col = c("white","black"), row_names_side = "left", column_names_side = "top", show_row_names = F, show_column_names = T,
                name = "Missingness Pattern", row_names_gp = gpar(fontsize = 10), column_names_gp = gpar(fontsize = 16))
  draw(ht2, heatmap_legend_side = "top")
}

#' Plot protein numbers
#'
#' \code{plot_numbers} generates a barplot of the number of identified proteins per sample.
#'
#' @param data SummerizedExperiment, Data object for which to plot protein numbers.
#' @return Barplot of the number of identified proteins per sample (generated by \code{\link{ggplot}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#' plot_numbers(example_se)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' plot_numbers(example_filter)
#' @export
plot_numbers <- function(data) {
  # Make a binary long data.frame (1 = valid value, 0 = missing value)
  df <- assay(data) %>% data.frame() %>% rownames_to_column() %>% gather(ID, bin, 2:ncol(.)) %>% mutate(bin = ifelse(is.na(bin), 0, 1))
  # Summarize the number of proteins identified per sample and generate a barplot
  stat <- df %>% group_by(ID) %>% summarize(n = n(), sum = sum(bin)) %>% left_join(., data.frame(colData(data)), by = "ID")
  ggplot(stat, aes(x = ID, y = sum, fill = condition)) + geom_bar(stat = "identity") + theme_bw() + labs(title = "Proteins per sample", x = "", y = "Number of ProteinGroups") + geom_hline(yintercept = unique(stat$n)) +
    theme(axis.text=element_text(size=12), axis.text.x = element_text(angle = 90, hjust = 1, size=10), axis.title=element_text(size=12,face="bold"), legend.text=element_text(size=10), legend.title = element_text(size=12,face="bold"), legend.position="right")
}

#' Plot protein overlap between samples
#'
#' \code{plot_frequency} generates a barplot of the protein overlap between samples
#'
#' @param data ExpressionSet, Data object for which to plot observation frequency.
#' @return Barplot of overlap of protein identifications between samples (generated by \code{\link{ggplot}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#' plot_frequency(example_se)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' plot_frequency(example_filter)
#' @export
plot_frequency <- function(data) {
  # Make a binary long data.frame (1 = valid value, 0 = missing value)
  df <- assay(data) %>% data.frame() %>% rownames_to_column() %>% gather(ID, bin, 2:ncol(.)) %>% mutate(bin = ifelse(is.na(bin), 0, 1))
  # Identify the number of experiments a protein was observed
  stat <- df %>% group_by(rowname) %>% summarize(sum = sum(bin))
  # Get the frequency of the number of experiments proteins were observerd and plot these numbers
  table <- table(stat$sum) %>% data.frame()
  ggplot(table, aes(x = Var1, y = Freq, fill = Var1)) + geom_bar(stat = "identity") + theme_bw() + labs(title = "Protein identifications overlap", x = "Identified in number of samples", y = "Number of ProteinGroups") + scale_fill_grey(start = 0.8, end = 0.2) +
    theme(axis.text=element_text(size=12), axis.text.x = element_text(angle = 90, hjust = 1, size=12), axis.title=element_text(size=12,face="bold"), legend.text=element_text(size=12), legend.title = element_text(size=12,face="bold"), legend.position="none")
}

#' Plot protein coverage in conditions
#'
#' \code{plot_coverage} generates a barplot of the protein coverage in samples.
#'
#' @param data ExpressionSet, Data object for which to plot observation frequency.
#' @return Barplot of protein coverage in samples (generated by \code{\link{ggplot}})
#' @examples
#' example <- UbiLength %>% filter(Reverse != "+", Potential.contaminant != "+")
#' example_unique <- unique_names(example, "Gene.names", "Protein.IDs", delim = ";")
#'
#' columns <- grep("LFQ.", colnames(example_unique))
#' exp_design <- UbiLength_ExpDesign
#' example_se <- make_se(example_unique, columns, exp_design)
#' plot_coverage(example_se)
#'
#' example_filter <- filter_missval(example_se, thr = 0)
#' plot_coverage(example_filter)
#' @export
plot_coverage <- function(data) {
  # Make a binary long data.frame (1 = valid value, 0 = missing value)
  df <- assay(data) %>% data.frame() %>% rownames_to_column() %>% gather(ID, bin, 2:ncol(.)) %>% mutate(bin = ifelse(is.na(bin), 0, 1))
  # Identify the number of experiments a protein was observed
  stat <- df %>% group_by(rowname) %>% summarize(sum = sum(bin))
  # Get the frequency of the number of experiments proteins were observerd and plot the cumulative sum of these numbers
  table <- table(stat$sum) %>% data.frame() %>% mutate(sum = rev(cumsum(rev(Freq))), pos = sum - (Freq / 2))
  ggplot(table, aes(x = "all", y = Freq, fill = Var1)) + geom_col(col = "white") + theme_bw() + labs(title = "Protein coverage in samples", x = "", y = "Number of ProteinGroups") + scale_fill_grey(start = 0.8, end = 0.2) +
    theme(axis.text=element_text(size=12), axis.text.x = element_blank(), axis.title=element_text(size=12,face="bold"), legend.text=element_text(size=12), legend.title = element_text(size=12,face="bold"), legend.position="right") +
    guides(fill=guide_legend(title="samples"))
}
