#' Plot PCA
#'
#' \code{plot_pca} generates a PCA plot using the top variable proteins.
#'
#' @param dep SummarizedExperiment,
#' Data object for which differentially enriched proteins are annotated
#' by \code{\link{test_diff}} and \code{\link{add_rejections}}.
#' @param x Integer,
#' The principle component to plot on the x-axis.
#' @param y Integer,
#' The principle component to plot on the y-axis.
#' @param n Integer,
#' The number of top variable proteins to consider.
#' @return A scatter plot (generated by \code{\link[ggplot2]{ggplot}}).
#' @examples
#' # load data
#' data <- UbiLength
#' data <- data[data$Reverse != '+' & data$Potential.contaminant != '+',]
#' exp_design <- UbiLength_ExpDesign
#'
#' data_unique <- make_unique(data, 'Gene.names', 'Protein.IDs', delim = ';')
#' columns <- grep('LFQ.', colnames(data_unique))
#' se <- make_se(data_unique, columns, exp_design)
#'
#' filt <- filter_missval(se, thr = 0)
#' norm <- normalize_vsn(filt)
#' imputed <- impute(norm, fun = 'MinProb', q = 0.01)
#'
#' diff <- test_diff(imputed, 'Ctrl', 'control')
#' dep <- add_rejections(diff, alpha = 0.05, lfc = 1)
#'
#' plot_pca(dep)
#' @export
plot_pca <- function(dep, x = 1, y = 2, n = 500) {
  if(is.numeric(x)) x <- as.integer(x)
  if(is.numeric(y)) y <- as.integer(y)
  if(is.numeric(n)) n <- as.integer(n)
  # Show error if inputs are not the required classes
  assertthat::assert_that(inherits(dep, "SummarizedExperiment"),
                          is.integer(x),
                          is.integer(y),
                          is.integer(n))

  # Check for valid x and y values
  if(x > ncol(dep) & x > ncol(dep)) {
    stop(paste0("'x' and/or 'y' arguments are not valid.\n",
                "Run plot_pca() with 'x' and 'y' <= ",
                ncol(dep),
                "."),
         call. = FALSE)
  }

  # Check for valid n value
  if(n > nrow(dep)) {
    stop(paste0("'n' argument is not valid.\n",
                "Run plot_pca() with 'n' <= ",
                nrow(dep),
                "."),
         call. = FALSE)
  }

  # Get the variance per protein and take the top n variable proteins
  var <- apply(assay(dep), 1, sd)
  df <- assay(dep)[order(var, decreasing = TRUE)[1:n],]

  # Calculate PCA
  pca <- prcomp(t(df), scale = FALSE)
  pca_df <- pca$x %>%
    data.frame() %>%
    rownames_to_column() %>%
    left_join(., data.frame(colData(dep)), by = c("rowname" = "ID"))

  # Calculate the percentage of variance explained
  percent <- round(100 * pca$sdev^2 / sum(pca$sdev^2), 1)
  PC_cols <- grep("^PC", colnames(pca_df))
  colnames(pca_df)[PC_cols] <- paste0(colnames(pca_df)[PC_cols], ": ", percent, "%")

  # Select the PC to plot
  pca_df$x <- pca_df[, PC_cols[x]]
  pca_df$y <- pca_df[, PC_cols[y]]

  # Plot the PCA
  pca_df$replicate <- as.factor(pca_df$replicate)
  ggplot(pca_df, aes(x = x, y = y, col = condition, shape = replicate)) +
    geom_point(size = 6) +
    labs(title = paste0("PCA plot - top ", n, " variable proteins"),
         x = colnames(pca_df)[PC_cols[x]],
         y = colnames(pca_df)[PC_cols[y]]) +
    theme_DEP1()
}

#' Plot correlation matrix
#'
#' \code{plot_corr} generates a Pearson correlation matrix.
#'
#' @param dep SummarizedExperiment,
#' Data object for which differentially enriched proteins are annotated
#' by \code{\link{test_diff}} and \code{\link{add_rejections}}.
#' @param significant Boolean,
#' Whether or not to filter for significant proteins.
#' @param lower Integer,
#' The lower limit of the color scale.
#' @param upper Integer,
#' The upper limit of the color scale.
#' @param pal Character,
#' The name of the color panel from \code{\link[RColorBrewer]{brewer.pal}}.
#' @param pal_rev Logical,
#' Whether or not to invert the color palette.
#' @return A heatmap plot (generated by \code{\link[ComplexHeatmap]{Heatmap}})
#' @examples
#' # load data
#' data <- UbiLength
#' data <- data[data$Reverse != '+' & data$Potential.contaminant != '+',]
#' exp_design <- UbiLength_ExpDesign
#'
#' data_unique <- make_unique(data, 'Gene.names', 'Protein.IDs', delim = ';')
#' columns <- grep('LFQ.', colnames(data_unique))
#' se <- make_se(data_unique, columns, exp_design)
#'
#' filt <- filter_missval(se, thr = 0)
#' norm <- normalize_vsn(filt)
#' imputed <- impute(norm, fun = 'MinProb', q = 0.01)
#'
#' diff <- test_diff(imputed, 'Ctrl', 'control')
#' dep <- add_rejections(diff, alpha = 0.05, lfc = 1)
#'
#' plot_corr(dep)
#' @export
plot_corr <- function(dep, significant = TRUE, lower = -1, upper = 1, pal = "PRGn", pal_rev = FALSE) {
  # Show error if inputs are not the required classes
  assertthat::assert_that(inherits(dep, "SummarizedExperiment"),
                          is.logical(significant),
                          is.numeric(lower),
                          is.numeric(upper),
                          is.character(pal),
                          is.logical(pal_rev))

  # Check for valid lower and upper values
  if(!(lower >= -1  & upper >= -1 & lower <= 1 & upper <= 1)) {
    stop(paste0("'lower' and/or 'upper' arguments are not valid.\n",
                "Run plot_pca() with 'lower' and 'upper' between -1 and 1."),
         call. = FALSE)
  }

  # Check for valid pal
  pals <- RColorBrewer::brewer.pal.info %>%
    rownames_to_column() %>%
    filter(category != "qual")
  if(!pal %in% pals$rowname) {
    stop(paste0("'", pal,"' is not a valid color panel",
                " (qualitative panels also not allowed).\n",
                "Run plot_pca() with one of the following 'pal' options: ",
                paste(pals$rowname, collapse = "', '"),
                "'."),
         call. = FALSE)
  }

  # Filter for significant proteins
  if(significant) {

    # Check for significant column
    if(!"significant" %in% colnames(rowData(dep))) {
      stop(paste0("'significant' column is not present in '",
                  deparse(substitute(dep)),
                  "'.\nRun add_rejections() to obtain the required column."),
           call. = FALSE)
    }

    dep <- dep[rowData(dep)$significant, ]
  }

  # Calculate correlation matrix
  corr_mat <- cor(assay(dep))

  # Plot heatmap
  ht1 = Heatmap(corr_mat,
                col = circlize::colorRamp2(
                  seq(lower, upper, ((upper-lower)/7)),
                  if(pal_rev) {
                    rev(RColorBrewer::brewer.pal(8, pal))
                  } else {
                    RColorBrewer::brewer.pal(8, pal)
                  }),
                cluster_columns = TRUE,
                cluster_rows = TRUE,
                na_col = "grey",
                clustering_distance_rows = "euclidean",
                clustering_distance_columns = "euclidean",
                row_names_side = "left",
                column_names_side = "top",
                show_row_names = TRUE,
                show_column_names = TRUE,
                heatmap_legend_param = list(color_bar = "continuous",
                                            legend_direction = "vertical",
                                            legend_width = unit(5, "cm"),
                                            title_position = "topcenter"),
                name = "Pearson correlation",
                column_names_gp = gpar(fontsize = 15),
                row_names_gp = gpar(fontsize = 15))
  draw(ht1, heatmap_legend_side = "right")
}
